--Conectar: mysql -h localhost -u root -p
--Digire a senha do banco de dados apos o comando.

CREATE DATABASE framework;

CREATE TABLE TBL_CLIENTE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	CODIGO BIGINT(20) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE = innoDB;

--Selecionar todos os usuarios cadastrados:
--SELECT * FROM TBL_CLIENTE;

CREATE TABLE TBL_NOTA_FISCAL_SERVICO (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	NUMERO BIGINT(20) NOT NULL, 
	DISCRIMINACAO_GERAL VARCHAR(100) NOT NULL,
	DATA DATETIME NOT NULL,
	VALOR DECIMAL(13, 2) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE = innoDB;

--Selecionar todas as notas cadastradas:
--SELECT * FROM TBL_NOTA_FISCAL_SERVICO;

CREATE TABLE `TBL_CLIENTE_NOTA_FISCAL_SERVICO` (
  `CLIENTE_ID` BIGINT NOT NULL ,
  `NFS_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`CLIENTE_ID`, `NFS_ID`) ,
  INDEX `FK_CLINFS_CLI` (`CLIENTE_ID` ASC) ,
  INDEX `FK_CLINFS_NFS` (`NFS_ID` ASC) ,
  CONSTRAINT `FK_CLINFS_CLI`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `TBL_CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CLINFS_NFS`
    FOREIGN KEY (`NFS_ID`)
    REFERENCES `TBL_NOTA_FISCAL_SERVICO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;